# Generated by Django 5.1.2 on 2025-02-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile_primary_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='primary_adress',
            new_name='primary_address',
        ),
    ]
