# Generated by Django 5.1.2 on 2025-02-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_primary_adress_profile_primary_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='quantity',
        ),
        migrations.AddField(
            model_name='buy',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
